export type NavSection =
  | 'dashboard'
  | 'events'
  | 'tickets'
  | 'sales'
  | 'crm'
  | 'checkin'
  | 'staff'
  | 'suppliers'
  | 'products'
  | 'inventory'
  | 'intelligence'
  | 'communication'
  | 'financial'
  | 'billing'
  | 'growth'
  | 'help'
  | 'settings'

export const defaultNavSection: NavSection = 'dashboard'
