import {
  ArrowRight,
  BarChart3,
  CalendarDays,
  CheckCircle2,
  ClipboardList,
  Eye,
  MessageSquare,
  QrCode,
  Settings,
  Smartphone,
  Tag,
  Users,
} from 'lucide-react'
import { PublicLayout } from '@/features/public'
import { usePublicLocale } from '@/features/public/lib/public-locale'
import { useSeoMeta } from '@/shared/lib'

const STEPS = [
  {
    number: '01',
    icon: CalendarDays,
    titlePt: 'Crie seu evento',
    titleEn: 'Create your event',
    descPt: 'Defina nome, data, local e capacidade. Adicione descricao, galeria de midia e pagina publica em minutos.',
    descEn: 'Set name, date, venue and capacity. Add description, media gallery and a public page in minutes.',
  },
  {
    number: '02',
    icon: Tag,
    titlePt: 'Configure ingressos e lotes',
    titleEn: 'Set up tickets and batches',
    descPt: 'Crie multiplos lotes com precos diferentes. A virada de lote acontece automaticamente por data ou por quantidade vendida.',
    descEn: 'Create multiple batches with different prices. Batch turnover happens automatically by date or sold quantity.',
  },
  {
    number: '03',
    icon: Smartphone,
    titlePt: 'Opere com o app Pulse',
    titleEn: 'Operate with the Pulse app',
    descPt: 'Check-in por QR code, gestao de staff, ocorrencias e supervisor em tempo real. Funciona offline.',
    descEn: 'QR code check-in, staff management, incidents and real-time supervisor view. Works offline.',
  },
  {
    number: '04',
    icon: BarChart3,
    titlePt: 'Analise os resultados',
    titleEn: 'Analyze the results',
    descPt: 'Dashboard com receita, conversao, ticket medio e presenca por hora. Repasse financeiro automatico apos o evento.',
    descEn: 'Dashboard with revenue, conversion, average ticket and hourly attendance. Automatic financial transfer after the event.',
  },
]

const ROLES = [
  {
    icon: ClipboardList,
    titlePt: 'Produtor',
    titleEn: 'Producer',
    bulletsPt: [
      'Cria e configura eventos, lotes e cupons',
      'Acompanha vendas e financeiro em tempo real',
      'Gerencia equipe, credenciamento e relatorios',
    ],
    bulletsEn: [
      'Creates and configures events, batches and coupons',
      'Tracks sales and finances in real time',
      'Manages staff, credentialing and reports',
    ],
  },
  {
    icon: Eye,
    titlePt: 'Supervisor',
    titleEn: 'Supervisor',
    bulletsPt: [
      'Ve o health score do evento ao vivo',
      'Aprova ocorrencias e decisoes criticas',
      'Acompanha mapa e posicao da equipe',
    ],
    bulletsEn: [
      'Views the live event health score',
      'Approves incidents and critical decisions',
      'Tracks staff map and positions',
    ],
  },
  {
    icon: Settings,
    titlePt: 'Operador',
    titleEn: 'Operator',
    bulletsPt: [
      'Realiza check-in por QR code ou manual',
      'Controla acesso por setor e capacidade',
      'Registra ocorrencias com foto e localizacao',
    ],
    bulletsEn: [
      'Performs QR code or manual check-in',
      'Controls access by sector and capacity',
      'Records incidents with photo and location',
    ],
  },
  {
    icon: Users,
    titlePt: 'Staff',
    titleEn: 'Staff',
    bulletsPt: [
      'Recebe convite por link sem precisar de conta',
      'Registra ponto de entrada e saida no app',
      'Recebe instrucoes e comunicados do supervisor',
    ],
    bulletsEn: [
      'Receives invite via link without needing an account',
      'Clocks in and out via the app',
      'Receives instructions and announcements from supervisor',
    ],
  },
  {
    icon: MessageSquare,
    titlePt: 'Promotor',
    titleEn: 'Promoter',
    bulletsPt: [
      'Acessa link unico com seu codigo de indicacao',
      'Acompanha vendas geradas pelo seu link',
      'Ve comissao acumulada em tempo real',
    ],
    bulletsEn: [
      'Accesses unique link with referral code',
      'Tracks sales generated by their link',
      'Views accumulated commission in real time',
    ],
  },
]

export function ComoFuncionaPage({ onLogin }: { onLogin: () => void }) {
  const { isPortuguese } = usePublicLocale()

  useSeoMeta({
    title: isPortuguese ? 'Como funciona a Pulse | Plataforma de eventos' : 'How Pulse Works | Event Platform',
    description: isPortuguese
      ? 'Crie, venda, opere e analise seus eventos em um unico lugar. Veja como a Pulse funciona do inicio ao fim.'
      : 'Create, sell, operate and analyze your events in one place. See how Pulse works from start to finish.',
  })

  return (
    <PublicLayout onLogin={onLogin}>
      {/* Hero */}
      <section className="relative overflow-hidden px-5 pb-16 pt-12 md:px-8 md:pb-24 md:pt-16 lg:px-10">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_30%_20%,rgba(0,87,231,0.18),transparent_50%),radial-gradient(circle_at_80%_60%,rgba(66,133,244,0.10),transparent_40%)]" />
        <div className="relative z-10 mx-auto max-w-[1540px]">
          <div className="text-[10px] uppercase tracking-[0.38em] text-[#4285F4]">
            {isPortuguese ? 'Como funciona' : 'How it works'}
          </div>
          <h1 className="mt-6 max-w-4xl text-[clamp(3rem,7vw,6rem)] font-bold leading-[0.88] tracking-[-0.04em] text-white">
            {isPortuguese
              ? 'Do ingresso ao encerramento. Tudo em um lugar.'
              : 'From ticket to closing. Everything in one place.'}
          </h1>
          <p className="mt-6 max-w-2xl text-lg leading-8 text-white/58">
            {isPortuguese
              ? 'A Pulse cobre todo o ciclo de vida do seu evento — da configuracao inicial ao repasse financeiro pos-evento.'
              : 'Pulse covers your entire event lifecycle — from initial setup to post-event financial transfer.'}
          </p>
        </div>
      </section>

      {/* Steps */}
      <section className="px-5 pb-20 md:px-8 lg:px-10">
        <div className="mx-auto max-w-[1540px]">
          <div className="grid gap-6 md:grid-cols-2">
            {STEPS.map((step) => {
              const Icon = step.icon
              return (
                <div
                  key={step.number}
                  className="group rounded-2xl border border-white/8 bg-white/[0.03] p-8 transition-all duration-300 hover:border-white/14 hover:bg-white/[0.05]"
                >
                  <div className="flex items-start gap-5">
                    <div className="font-mono text-4xl font-bold text-[#0057E7] opacity-60">{step.number}</div>
                    <div className="flex-1">
                      <div className="mb-4 flex h-11 w-11 items-center justify-center rounded-xl border border-[#0057E7]/20 bg-[#0057E7]/10 text-[#4285F4]">
                        <Icon className="h-5 w-5" />
                      </div>
                      <h3 className="text-xl font-bold text-white">
                        {isPortuguese ? step.titlePt : step.titleEn}
                      </h3>
                      <p className="mt-3 text-sm leading-7 text-white/50">
                        {isPortuguese ? step.descPt : step.descEn}
                      </p>
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      </section>

      {/* Roles section */}
      <section className="px-5 pb-20 md:px-8 lg:px-10">
        <div className="mx-auto max-w-[1540px]">
          <div className="mb-12">
            <div className="text-[10px] uppercase tracking-[0.38em] text-[#4285F4]">
              {isPortuguese ? 'Para cada papel da sua equipe' : 'For every role on your team'}
            </div>
            <h2 className="mt-5 max-w-2xl text-[clamp(2.4rem,5vw,4rem)] font-bold leading-[0.9] tracking-[-0.03em] text-white">
              {isPortuguese
                ? 'Cada pessoa tem o que precisa. Nada a mais.'
                : 'Every person has what they need. Nothing more.'}
            </h2>
          </div>

          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {ROLES.map((role) => {
              const Icon = role.icon
              return (
                <div
                  key={role.titlePt}
                  className="rounded-2xl border border-white/8 bg-white/[0.03] p-6 transition-all hover:border-white/14 hover:bg-white/[0.05]"
                >
                  <div className="mb-4 flex h-11 w-11 items-center justify-center rounded-xl border border-[#0057E7]/20 bg-[#0057E7]/10 text-[#4285F4]">
                    <Icon className="h-5 w-5" />
                  </div>
                  <h3 className="text-lg font-bold text-white">
                    {isPortuguese ? role.titlePt : role.titleEn}
                  </h3>
                  <ul className="mt-4 space-y-2">
                    {(isPortuguese ? role.bulletsPt : role.bulletsEn).map((item) => (
                      <li key={item} className="flex items-start gap-2.5 text-sm text-white/50">
                        <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[#4285F4]" />
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>
              )
            })}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="px-5 pb-20 md:px-8 lg:px-10">
        <div className="mx-auto max-w-[1540px]">
          <div className="relative overflow-hidden rounded-2xl border border-white/8 bg-[linear-gradient(135deg,rgba(0,87,231,0.20)_0%,rgba(10,10,10,0.96)_50%,rgba(66,133,244,0.08)_100%)] px-8 py-16 text-center lg:px-16 lg:py-20">
            <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(0,87,231,0.25),transparent_60%)]" />
            <div className="relative z-10">
              <div className="mb-3 flex items-center justify-center">
                <QrCode className="h-8 w-8 text-[#4285F4]" />
              </div>
              <h2 className="text-[clamp(2.6rem,5vw,4.8rem)] font-bold leading-[0.88] tracking-[-0.04em] text-white">
                {isPortuguese ? 'Crie seu primeiro evento gratis.' : 'Create your first event for free.'}
              </h2>
              <p className="mx-auto mt-5 max-w-xl text-base leading-8 text-white/50">
                {isPortuguese
                  ? 'Sem cartao de credito. Sem mensalidade. So paga quando vender.'
                  : 'No credit card. No monthly fee. Pay only when you sell.'}
              </p>
              <div className="mt-10 flex flex-wrap items-center justify-center gap-4">
                <a
                  href="/create-event"
                  className="inline-flex items-center gap-2 rounded-full bg-[#0057E7] px-7 py-4 text-sm font-bold uppercase tracking-[0.18em] text-white shadow-[0_16px_40px_rgba(0,87,231,0.35)] transition-all hover:-translate-y-0.5 hover:bg-[#4285F4]"
                >
                  {isPortuguese ? 'Criar evento gratis' : 'Create free event'}
                  <ArrowRight className="h-4 w-4" />
                </a>
                <a
                  href="https://wa.me/14698629040"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 rounded-full border border-white/18 px-7 py-4 text-sm font-medium uppercase tracking-[0.18em] text-white/70 transition-all hover:border-white/28 hover:text-white"
                >
                  {isPortuguese ? 'Falar com a equipe' : 'Talk to the team'}
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>
    </PublicLayout>
  )
}
